### ISSUE TITLE
Captcha code entered invalid

### ISSUE THREAD

**Issue by joserafael** [donovan-duplessis/cakephp-captcha#10]
Hello again. When I write the code cant validate. All the time show the message "Captcha code entered invalid".

I did a copy Contact MVC and happend all time.

What could be happend.
![captura de pantalla de 2014-09-29 18 01 55](https://cloud.githubusercontent.com/assets/60098/4450687/6c08ff30-4828-11e4-9bde-cd83983daefc.png)

Sorry my english :-)

**Comment by donovan-duplessis** [comment]
Hi Jose,

Would you mind just zipping up your code and sending it to me via email, it would probably take quicker for me to look at.

Things to lookout for:
- Route names must be configured correctly.
- The Behaviour field names must match the routes and the view inputs

Cheers,
Donovan

**Comment by joserafael** [comment]
Hello Donovan. You can download my code in https://github.com/joserafael/captcha
Thank you very much :+1:

**Comment by donovan-duplessis** [comment]
Hey Jose,

I see in your repository that the beforeValidate method has not been updated with that strict problem in your first issue.  Can you please update it according to that issue first and test again?

I am still looking at the code but it mostly looks correct.

Regards,
Donovan

**Comment by joserafael** [comment]
Hello Donovan, the beforeValidate method has been updated. The issue continue :-(

Thank you very much.

**Comment by donovan-duplessis** [comment]
Hey Jose,

Are you still running CakePHP 2.5.4?  If so, I will load it onto my demo server at captcha.baselocker.com and install the Captcha code and see if it runs.

Maybe it is now not compatible with the CakePHP version you are using.

Regards,
Donovan

**Comment by joserafael** [comment]
Yes, im using 2.5.4 version. I will try with a older version.

**Comment by donovan-duplessis** [comment]
Okay, so I got the strict error in 2.5.4 which I then fixed.  I loaded the files into the new 2.5.4 framework and everything worked perfectly.

Now I need to understand why your code is not working.

Can you just quickly do the following:
- Start with a brand new 2.5.4 install
- Clone the cakephp-captcha repository
- Change the beforeValidate() method to include $options = array()
- In the new 2.5.4 framework go to the app folder and just link in every file from the cakephp-captcha repository folder:

`<cakephp-captcha-repo>` is the folder where you cloned the cakephp-captcha repository into

``` bash
ln -s <cakephp-captcha-repo>/Model/Contact.php Model/Contact.php
ln -s <cakephp-captcha-repo>/Model/Behavior/CaptchaBehavior.php Model/Behavior/CaptchaBehavior.php
ln -s <cakephp-captcha-repo>/Controller/ContactsController.php Controller/ContactsController.php 
ln -s <cakephp-captcha-repo>/Controller/Component/CaptchaComponent.php Controller/Component/CaptchaComponent.php 
ln -s <cakephp-captcha-repo>/View/Contacts View/Contacts
ln -s <cakephp-captcha-repo>/View/Layouts/default.ctp View/Layouts/default.ctp 
ln -s <cakephp-captcha-repo>/View/Elements/flash_good.ctp View/Elements/flash_good.ctp
ln -s <cakephp-captcha-repo>/Lib/Fonts Lib/Fonts
```

`** If you do not want to use symbolic links, then just copy the files above into the right places`
- Setup default '/' route:

``` php
Router::connect('/', array('controller' => 'contacts', 'action' => 'index'));
```
- Add captcha image routes:

``` php
Router::connect('/captchas/captcha.jpg', array('controller' => 'contacts', 'action' => 'captcha'));
Router::connect('/captchas/captcha-2.jpg', array('controller' => 'contacts', 'action' => 'captcha'));
```

Then just restart the php server and let me know if it is working?

`** I just updated the demo at captcha.baselocker.com and it is running 2.5.4`

**Comment by donovan-duplessis** [comment]
Hi Jose,

Can I close this issue?

Regards,
Donovan
