### ISSUE TITLE
Image Loading Issue

### ISSUE THREAD

**Issue by siddiqicps** [donovan-duplessis/cakephp-captcha#11]
Dear  Donovan,
                           I have implemented your captcha component in the way you have described but it still not showing image. And when I opened image path in new window it this message
"http://localhost/vteme/img/captcha.jpg can not be displayed because it contains error".
Please suggest me the solution.

**Comment by donovan-duplessis** [comment]
Hey There,

Just to debug a few things:

1) Have you added the routes correctly?
2) Have you installed the imagemagick library?  This is required for the image generation.

Can you set the debug level of cakephp to 2 (verbose) and maybe it will give us a better description of your problem?

Essentially the actual controller method (in my example) displays the image.  The image route is just an alias to this method.

If you browse to http://localhost/vtheme/contacts/captcha what does it give you?

Regards,
Donovan

**Comment by siddiqicps** [comment]
Dear Donovan,
                          Hope you are doing well. I have checked all the settings you have mentioned above. Also I didn't installed imagemagick library as gd2 is already enabled in wamp. Is it required to install imagemagick library too.
Also I have checked this url  http://localhost/vteme/postads/captcha in the browser and it shows a broken image.

Regards,
Siddiqi

**Comment by donovan-duplessis** [comment]
Hey Siddiqi,

Actually, the gd library is perfect!

If possible, could you zip up your code and email it to me?  It will probably be easier to spot the issue.  I can test it pretty quickly for you.

Regards,
Donovan

**Comment by siddiqicps** [comment]
Dear Donovan,
                       I have attached here sample code please give it a
look.

**Comment by donovan-duplessis** [comment]
Hey Siddiqi,

Glad I could help in resolving your issue.

Regards,
Donovan
