### ISSUE TITLE
empty image box for captcha

### ISSUE THREAD

**Issue by SirbitoX** [donovan-duplessis/cakephp-captcha#13]
Hi,

I'm using this plugin in my codes. I have used it before in other projects too and it was perfect. But in my current project it doesn't show the captcha image (it shows an empty box). I've tested and compared all the steps with the other projects. Every thing is good in codes.
I set the debug to 2 but it didn't show anything.
I've installed php-gd on my server and test all all the relevant functions and they worked fine.
Could you help me? please.

**Comment by SirbitoX** [comment]
I changed:
`php Router::connect('/img/captcha.jpg', array('controller' => 'users', 'action' => 'captcha'));` to `php Router::connect('/img/captcha.jpg', array('plugin' => 'captcha', 'controller' => 'contacts', 'action' => 'captcha'));` and it works fine. And again I check both of them and the codes are same!!!!
Any idea???

**Comment by SDC2012** [comment]
Hey Saeed,

Sorry for the late reply, I have been on holiday.

The virtual captcha image route essentially maps to the controller action
(captcha).

If you browse directly to the image route is it still blank even if you put
debug mode on?

So browse to http://<server>/img/captcha.jpg and what does it output?

Those 2 routes of yours are identical so they will always generate the same
image, you will need to put a different image name in the second route.

I'm thinking maybe you can paste me your controller and view code and I can
have a look at it quickly?

Regards,
Donovan

**Comment by SirbitoX** [comment]
Hi Donovan,

> If you browse directly to the image route is it still blank even if you put debug mode on?

yes, It was empty when I set the route to my action in my controller but when I used the action of the plugin it showed me the captcha image correctly.

> I'm thinking maybe you can paste me your controller and view code and I can have a look at it quickly?

in `UserController.php` in my codes:

``` php
    public function captcha() {
        $this->autoRender = false;
        $this->Captcha->generate();
    }
```

in `ContactsController.php` of the captcha plugin:

``` php
    public function captcha() {
        $this->autoRender = false;
        $captcha = basename($this->params['url']['url'], '.jpg');
        $this->Captcha->generate($captcha);
    }
```

I've pasted the routers in earlier comment.

Thanks.

**Comment by donovan-duplessis** [comment]
Hey Saeed,

You are missing the following in the users controller captcha method:

``` ruby
$captcha = basename($this->params['url']['url'], '.jpg');
```

It uses that url image name to determine which captcha the image was linked to as the plugin supports multiple captcha components on one form.  So each route supports one captcha control, but the image filenames will be difference per route.

eg: captcha.jpg, captcha-1.jpg etc

So essentially you can change your route back:

``` php
Router::connect('/img/captcha.jpg', array('controller' => 'users', 'action' => 'captcha'));
```

and adjust the captcha method like this in the users controller:

``` php
public function captcha() {
    $this->autoRender = false;
    $captcha = basename($this->params['url']['url'], '.jpg');
    $this->Captcha->generate($captcha);
}
```

In the users controller you will also define how many captcha controls you want on the form (this corresponds to the image name in the route definition), for now just one:

``` php
/**
     * Captcha field definitions
     *
     * @var array
     * @access public
     */
    public $captchas = array('captcha');
```

Then in the view you can use the code from the contacts example in the plugin.

Please let me know how this goes?

Regards,
Donovan
