### ISSUE TITLE
Image is not loading

### ISSUE THREAD

**Issue by vahidrajaeivr** [donovan-duplessis/cakephp-captcha#5]
Hi
I am using cakephp 2.3.5
Image is not loading.
Any advise :(

**Comment by vahidrajaeivr** [comment]
Got it. For got to add 
Router::connect('/img/captcha.jpg', array('controller' => 'users', 'action' => 'captcha'));

**Comment by donovan-duplessis** [comment]
Ah, yip that is it!  it is nifty to create that route to "seem" like a
genuine image on the server.

I hope this is working for you the way you expect?  If you have any more
issues just shout and I will help.

**Comment by vahidrajaeivr** [comment]
Thank you for your quick response. did you think about reload the image.e.g.

Can't read? Reload Image... bang

**Comment by donovan-duplessis** [comment]
HI,

I have updated the sample code contained in the repository (contacts) to reload the capture image via jQuery.

You can see it in action at [captcha.baselocker.com](http://captcha.baselocker.com)

Regards,
Donovan

**Comment by vahidrajaeivr** [comment]
Cooliyoooooooooooo That's what I wanted.
Cheers mate.
I am using it in my project :)
