### ISSUE TITLE
2 captchas on same page - shows same image

### ISSUE THREAD

**Issue by mubasshir** [donovan-duplessis/cakephp-captcha#6]
Hi, if somehow we have two forms on same page and both using captcha, in that case they show same image of captcha.

**Comment by donovan-duplessis** [comment]
Hi Mubasshir,

I never actually catered for multiple Captchas on the same page, but I am currently modifying it to support your request.  I should have the new version up later today.

Thanks for your support,
Donovan

**Comment by donovan-duplessis** [comment]
Hi Mubasshir,

I have updated the codebase and the documentation with support for multiple captcha controls on the same form.

Regards,
Donovan
