### ISSUE TITLE
Strict

### ISSUE THREAD

**Issue by joserafael** [donovan-duplessis/cakephp-captcha#9]
Hello. Im using cakephp 2.5.4. show the next warning: 

Strict (2048): Declaration of CaptchaBehavior::beforeValidate() should be compatible with ModelBehavior::beforeValidate(Model $model, $options = Array) [APP/Model/Behavior/CaptchaBehavior.php, line 29]

Wath could be happen?

**Comment by donovan-duplessis** [comment]
Hi Jose,

It looks like they have changed the beforeValidate() function definition to include an options array in your newer version of CakePHP.

Could you please open `Model/Behavior/CaptchaBehavior.php` and go to line 94 and change:

``` php
public function beforeValidate(Model $model) {
```

to

``` php
public function beforeValidate(Model $model, $options = array())  {
```

That should conform to their new method.

Could you please let me know if this clears the strict warning?  If it does I will patch the code to include this fix.

Thanks for letting me know,
Donovan

**Comment by joserafael** [comment]
I did the change and this warning is clear. Thanks Donovan :-)

**Comment by ghost** [comment]
Thank you.

**Comment by chinmay235** [comment]
@donovan-duplessis Thanks for answering here.

I have changed this line now its working fine. :+1: 

```
public function beforeValidate(Model $model, $options = array())  {
```
